{% set version_data = load_file_regex(
    load_file='sphinx_tabs/__init__.py',
    regex_pattern='__version__\\s*=\\s*\"([^\"]+)\"'
) %}
{% set version = version_data[1] %}

package:
  name: sphinx-tabs
  version: "{{ version }}"

source:
  path: ../../

build:
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools >=64
  run:
    - python
    - sphinx >=1.8
    - pygments
    - docutils

test:
  imports:
    - sphinx_tabs
    - sphinx_tabs.tabs
  requires:
    - pip
  commands:
    - pip check

about:
  home: "https://github.com/executablebooks/sphinx-tabs"
  license: MIT
  summary: "Tabbed views for Sphinx"
  description: "Create tabbed content in Sphinx documentation when building HTML."
  dev_url: "https://github.com/executablebooks/sphinx-tabs"
  doc_url: "https://sphinx-tabs.readthedocs.io"
