package:
  name: depdigest
  version: "{{ environ['GIT_DESCRIBE_TAG'] }}"
source:
  path: ../../
build:
  number: 1
requirements:
  build:
  - python
  - pip
  - setuptools >=61.0
  - versioningit >=3.0
  run:
  - python
  - smonitor
about:
  home: "https://www.uibcdf.org"
  license: MIT License
  summary: ''
  description: 'This library provides some useful methods to work with quantities

    '
  dev_url: "https://www.github.com/uibcdf/depdigest"
  doc_url: "https://www.uibcdf.org/depdigest"
